.ORG 000H

  ;INGRESAMOS DATOS DE PRUEBA
  MVI H, 10H
  MVI L, 50H

  MVI M, E7H     ;7220(PRUEBA 1000 EN 1000 34H) 7200(PRUEBA 1000 EN 1000 20H)   7000(PRUEBA 1000 EN 1000 58H)      (NUMEROS PRUEBA MERNOR A 100 3FH=63D)
  INR L
  MVI M, 03H     ;7220(PRUEBA 1000 EN E1000 1CH) 7200(PRUEBA 1000 EN E1000 1CH)  7000(PRUEBA 1000 EN E1000 1BH)     (NUMEROS PRUEBA MERNOR A 100 00H=00D)
  ;HASTA AQUI SE BORRARA EN LA IMPLEMENTACIÓN




  MVI D, 10H
  MVI B, 10H

  MVI A,03H                     ;PONEMOS UN CERO EN EL ACUMULADOR
  CMP M                         ;COMPARAMOS A CON EL NEABLE ALTO PARA SABER SI ESTE VALE cero (A<M -> C=1 Y SALTA)
  JC NeableCero
  JZ MenorA1000
    ;AQUI ADENTRO SABEMOS QUE EL NEABLE ALTO VALE CERO, POR LO TANTO EL MAXIMO NUMERO
    ;EN EL NEABLE BAJO ES 255, CON ESTO PODEMO EMPEZAR APREGUNTAR DESDE AQUI

    MVI L,50H                   ;DECREMENTAMOS L PARA OBTENER EL NEABLE BAJO
    MOV A, M                    ;TRAEMOS EL NEABLE BAJO AL ACUMULADOR
    CPI 64H                     ;COMPARAMOS SI ES MENOR A 100H  (A<v -> C=1 Y SALTA)
    JNC Menor100

      CALL CICLO10SPECIAL
      MOV A, M                  ;TRAEMOS EL NUMERO A CONVERTIR AL ACUMULADOR
      ADD C                     ;SUMAMOS EL EL NUMERO A SUMAR CON EL NUMERO A CONVERTIR
      MOV M, A                  ;MOVEMOS EL RESULTADO AL NEABLE BAJO PARA MOSTRARLO EN EL DISPLAY

      ;LLAMAMOS METODO PARA ROTAR Y MOSTRAR SOLO DOS NUMEROS, A ESTE ROTAR NO SE LE HARAN CAMBIOS

      HLT                       ;forzamos el cierre del programa


;DESARROLLAREMOS ESTA PARTE AL FINAL
      MenorA1000: ANA A
      MVI L, 50H
      MVI A, E8H
      CMP M
      JC MAYORA999
    Menor100:   MVI L, 60H
      MVI M, 64H
      INR L
      MVI M, 9CH
      CALL CICLO100Y10

      ;actualizamos el dato temporal
      MVI C, 52H
      MVI E, 58H
      LDAX B
      STAX D
      INX B
      INX D
      LDAX B
      STAX D

      MVI L, 60H
      MVI M, 0AH
      INR L
      MVI M, 06H
      CALL CICLO100Y10     ;EL RESULTADO DE C PODEMOS SUMARLO AL NEABLE BAJO DEL RESULTADO

      CALL SumarResultado


      ;SOLO PARA LAS PRUEBAS
      MVI L, 50H
      MOV A, M
      OUT 00H
      INR L
      MOV A, M
      OUT 01H

      HLT


    ;LLAMAMOS METODO PARA ROTAR Y MOSTRAR SOLO TRES NUMEROS, A ESTE ROTAR NO SE LE HARAN CAMBIOS

    MAYORA999: ANA A
  NeableCero: CALL CICLO1000 ;PONER AQUI COMPROBACION PARA VER SI ES MENOR A MIL, SINO HACER CICLO1000

  ;Guardamos el numero en la posicion que necesitamos
  MVI C, 52H
  MVI E, 58H
  LDAX B
  STAX D
  INX B
  INX D
  LDAX B
  STAX D

  MVI L, 60H
  MVI M, 64H
  INR L
  MVI M, 9CH
  CALL CICLO100Y10

  ;actualizamos el dato temporal
  MVI C, 52H
  MVI E, 58H
  LDAX B
  STAX D
  INX B
  INX D
  LDAX B
  STAX D

  MVI L, 60H
  MVI M, 0AH
  INR L
  MVI M, 06H
  CALL CICLO100Y10     ;EL RESULTADO DE C PODEMOS SUMARLO AL NEABLE BAJO DEL RESULTADO


  CALL SumarResultado


  ;SOLO PARA LAS PRUEBAS
  MVI L, 50H
  MOV A, M
  OUT 00H
  INR L
  MOV A, M
  OUT 01H
HLT                              ;forzamos el cierre del programa





;>>>>>>>CICLO DE 1000 EN 1000<<<<<<<<<<
CICLO1000: ANA A                    ;COLOCAMOS EL ACARREO EN CERO

  ;SUMAMOS EL NEABLE BAJO DEL NUMERO A COMPARAR
  C1000:MVI E, 58H        ;HUBICAMOS EL NEABLE BAJO DEL NUMERO A COMPARAR
    ANA A                 ;<---- POR SI ACASO
    LDAX D                ;TRAEMOS EL CONTENIDO DEL NEABLE BAJO DE B PARA SUMARLO CON
    ADI E8H               ;SUMAMOS EL 18H DEL NEABLE BAJO DE 3096
    STAX D                ;ENVIAMOS EL NUMERO SUMADO AL NEABLE BAJO

    ;SUMAMOS EL ACARREO QUE DEJO EL NEABLE BAJO AL NEABLE ALTO
    INR E    ;!           ;INCREMENTAMOS &DE PARA USAR EL NEABLE ALTO
    LDAX D                ;TRAEMOS EL CONTENIDO DEL NEABLE ALTO PARA SUMARLO CON EL ACARREO
    ACI 00H               ;SUMAMOS 00H + EL CONTENIDO DEL ACUMULADOR + EL ACARREO QUE DEJO EL NEABLE BAJO (SI LO HAY)

    ;SUMAMOS EL NEABLO ALTO DEL NUMERO A COMPARAR
    ADI 03H               ;LE SUMAMOS EL DATO AL NEABLE ALTO
    STAX D                ;ENVIAMOS EL NUMERO SUMADO + EL ACARREO DEL NEABLE BAJO (SI LO HUBO) AL NEABLE ALTO

    ANA A
    ;Hacemos la comparacion
    MVI L, 51H         ;TRAEMOS EL NEABLE ALTO DEL NUMERO MULTIPLICADO PARA COMPARARLOS PRIMERO
    XCHG                    ;CAMBIE  DE CON HL
    LDAX D                  ;TRAEMOS EL NEABLE ALTO DEL NUMERO A COMPARAR PARA COMPARLO CON EL NEABLE ALTO DEL DATO ORIGINAL
    CMP M                   ;COMPARAMOS SI EL NEABLE A COMPARAR (03) ES MENOR AL NEABLE ALTO DEL DATO MULTIPLICADO (A<M -> C=1 Y SALTA)

    JC NeablePequeÃ±o         ;SI EL NUMERO ES MENOR A 1000 ACABAMOS LA FUNCION, SINO ENTRAMOS A SUMAR DE 1000 EN 1000

      ;Guardamos el numero en la posicion que necesitamos
      MVI C, 58H
      MVI E, 52H
      LDAX B
      STAX D
      INR C
      INR E
      LDAX B
      STAX D


      MVI C, 54H             ;INICIAMOS &BC EN 1054, AQUI Y EN 1055 GUARDAREMOS EL NUMERO A SUMAR
      ;SUMAMOS EL NEABLE BAJO DEL NUMERO A SUMAR
      ANA A ;<---- POR SI ACASO
      LDAX B                ;TRAEMOS EL CONTENIDO DEL NEABLE BAJO DE B PARA SUMARLO CON
      ADI 18H               ;SUMAMOS EL 18H DEL NEABLE BAJO DE 3096
      STAX B                ;ENVIAMOS EL NUMERO SUMADO AL NEABLE BAJO

      ;SUMAMOS EL ACARREO QUE DEJO EL NEABLE BAJO AL NEABLE ALTO
      INR C    ;!           ;INCREMENTAMOS &DE PARA USAR EL NEABLE ALTO
      LDAX B                ;TRAEMOS EL CONTENIDO DEL NEABLE ALTO PARA SUMARLO CON EL ACARREO
      ACI 00H               ;SUMAMOS 00H + EL CONTENIDO DEL ACUMULADOR + EL ACARREO QUE DEJO EL NEABLE BAJO (SI LO HAY)


      ;SUMAMOS EL NEABLO ALTO DEL NUMERO A SUMAR
      ADI 0CH               ;LE SUMAMOS EL DATO AL NEABLE ALTO
      STAX B                ;ENVIAMOS EL NUMERO SUMADO + EL ACARREO DEL NEABLE BAJO (SI LO HUBO) AL NEABLE ALTO

  JMP C1000          ;Nos de volvemos a C1
NeablePequeÃ±o: RET
;>>>>>>>FIN CICLO DE 1000 EN 1000<<<<<<<<<<



;>>>>>CICLO DE 100 EN 100<<<<<<<<<<
CICLO100Y10: ANA A             ;POR SI YA HAY ACARREO

  C100: MVI E, 58H          ;INICIAMOS &DE EN 1052, AQUI GUARDAREMOS EL NUMERO A COMPARAR
    LDAX D                  ;TRAEMOS EL CONTENIDO DEL NEABLE BAJO DEL NUMERO A COMPARAR PARA SUMARLE 100
    MVI L, 60H
    ADD M                   ;SUMAMOS 100(64H) AL NEABLE BAJO
    STAX D                  ;INGRESAMOS EL RESULTADO AL NEABLE BAJO DEL NUMERO A COPARAR

    ;POR SI QUEDA ACARREO CON EL NUMERO A COMPARAR
    INR E                   ;INCREMENTAMOS &DE PARA USAR EL NEABLE ALTO DEL NUMERO A COMPARAR
    LDAX D                  ;TRAEMOS EL CONTENIDO DEL NEABLE ALTO DEL NUMERO A COMPARAR AL ACUMULADOR PARA SUMARLO CON EL ACARREO
    ACI 00H                 ;SUMAMOS 00H + EL CONTENIDO DEL ACUMULADOR + EL ACARREO QUE DEJO EL NEABLE BAJO (SI LO HAY)
    STAX D                  ;INGRESAMOS EL RESULTADO AL NEABLE BAJO DEL NUMERO A COPARAR

    ANA A                    ;COLOCAMOS EL ACARREO EN CERO

    ;COMPARAR LOS NEABLES ALTOS PARA VER CUAL ES MAYOR
    MVI L, 51H          ;TRAEMOS EL NEABLE ALTO DEL NUMERO MULTIPLICADO PARA COMPARARLOS PRIMERO
    XCHG                    ;CAMBIE  DE CON HL
    LDAX D                  ;TRAEMOS EL NEABLE ALTO DEL NUMERO A COMPARAR PARA COMPARLO CON EL NEABLE ALTO DEL DATO ORIGINAL
    CMP M                   ;COMPARAMOS SI EL NEABLE A COMPARAR ES MENOR AL NEABLE ALTO DEL DATO MULTIPLICADO (A<M -> C=1 Y SALTA)
  JZ Iguales
    JC NeablePequeÃ±o100       ;DEPENDIENDO DE LA ITERACION PODEMOS ACABAR O PROSEGUIR CONEL CICLO
        BajosIguales: ANA A

        VUELVE:MVI C, 54H             ;INICIAMOS &BC EN 1054, AQUI Y EN 1055 GUARDAREMOS EL NUMERO A SUMAR
        ;SUMAMOS EL NEABLE BAJO DEL NUMERO A SUMAR
        ANA A                 ;<---- POR SI ACASO
        LDAX B                ;TRAEMOS EL CONTENIDO DEL NEABLE BAJO DE B PARA SUMARLO CON
        MVI L, 61H
        ADD M                 ;SUMAMOS EL 9CH DEL NEABLE BAJO DE 156
        STAX B                ;ENVIAMOS EL NUMERO SUMADO AL NEABLE BAJO

        ;SUMAMOS EL ACARREO QUE DEJO EL NEABLE BAJO AL NEABLE ALTO
        INR C    ;!           ;INCREMENTAMOS &DE PARA USAR EL NEABLE ALTO
        LDAX B                ;TRAEMOS EL CONTENIDO DEL NEABLE ALTO PARA SUMARLO CON EL ACARREO
        ACI 00H               ;SUMAMOS 00H + EL CONTENIDO DEL ACUMULADOR + EL ACARREO QUE DEJO EL NEABLE BAJO (SI LO HAY)
        STAX B                ;ENVIAMOS EL NUMERO SUMADO + EL ACARREO DEL NEABLE BAJO (SI LO HUBO) AL NEABLE ALTO

        ;Guardamos el numero en la posicion que necesitamos
        MVI C, 58H
        MVI E, 52H
        LDAX B
        STAX D
        INR C
        INR E
        LDAX B
        STAX D

      JMP C100          ;Nos de volvemos a C1
    Iguales: ANA A

        ;COMPARAR LOS NEABLES BAJOS
        MVI E, 58H
        MVI L, 50H          ;TRAEMOS EL NEABLE ALTO DEL NUMERO MULTIPLICADO PARA COMPARARLOS PRIMERO
        ;XCHG                    ;CAMBIE  DE CON HL
        LDAX D                  ;TRAEMOS EL NEABLE ALTO DEL NUMERO A COMPARAR PARA COMPARLO CON EL NEABLE ALTO DEL DATO ORIGINAL
        CMP M                   ;COMPARAMOS SI EL NEABLE A COMPARAR ES MENOR AL NEABLE ALTO DEL DATO MULTIPLICADO (A<M -> C=1 Y SALTA)
      JZ BajosIguales
    JC VUELVE

NeablePequeÃ±o100:RET
;>>>>>FIN CICLO DE 100 EN 100<<<<<<<<<<




;>>>>>>>CICLO DE 10 EN 10 ESPECIAL<<<<<<<<<<
CICLO10SPECIAL: MVI L,50H
 MOV B,M			 ;Guardamos el dato en el registro B
 MVI D,0AH     ;Inicializamos el registro D con 0AH para los limites de 10

 C10SPECIAL:MOV A,B		 ;Recuperamos el dato de B en el acumulador (necesario para lo siguientes pasos)
  CMP D        ;Comparamos con D, si es menor saltamos al final y sumamos C que
 JC C102SPECIAL				 ;idealmente C debe valer cero para este caso

 MOV A,C	      ;Movemos el contenido de C al acumulador
	ADI 06H       ;Sumamos 06H a este contenido
 MOV C,A       ;Guardamos el resultado en C nuevamente
 MOV A,D       ;recuperamos el valor de D
	ADI 0AH       ;y le sumamos 0AH para la siguiente iteracion
	MOV D,A       ;Nuevamente guardamos el valor
 JMP C10SPECIAL          ;Nos de volvemos a C1

 C102SPECIAL: RET
;>>>>>>>FIN CICLO DE 10 EN 10 ESPECIAL<<<<<<<<<<


;>>>>>>>SUMAR RESULTADO<<<<<<<<<<
SumarResultado:MVI L,50H    ;APUNTAMOS A LA UBICACION DE NEABLE BAJO DEL NUMERO A CONVERTIR
  MVI C,54H                 ;APUNTAMOS AL NEABLE BAJO DEL NUMERO A SUMAR
  LDAX B                    ;TRAEMOS EL CONTENIDO DEL NEABLE BAJO DEL NUMERO A SUMAR
  ADD M                     ;SUMAMOS EL NEABLE BAJO DEL NUMERO A SUAMAR CON EL NEABLE BAJO DEL NUMERO A CONVERTIR
  MOV M, A                  ;MOVEMOS EL RESULTADO A 1050

  ;POR SI HAY ACARREO EN LA SUMA DE LOS NEABLES BAJOS
  INX H                     ;INCREMENTAMOS &HL PARA USAR EL NEABLE ALTO DEL NUMERO A CONVERTIR
  MOV A,M                   ;TRAEMOS EL CONTENIDO DEL NEABLE ALTO DEL NUMERO A CONVERTIR PARA SUMARLO CON EL ACARREO
  ACI 00H                   ;SUMAMOS 00H + EL CONTENIDO DEL ACUMULADOR + EL ACARREO QUE DEJO EL NEABLE BAJO (SI LO HAY)


  MVI L, 55H                ;APUNTAMOS CON HL AL NEABLE ALTO DEL NUMERO A SUMAR
  ADD M                     ;SUMAMOS EL CONTENIDO DEL NEABLE ALTO DEL NUMERO A SUMAR+EL ACARREO+EL NUMERO CONVERTIDO
  MVI L, 51H                ;APUNTAMOS A LA POSICION DEL NEABLE ALTO DEL NUMERO A CONVERTIR
  MOV M, A                  ;GUARDAMOS EL RESULTADO DE LAS SUMAS DE NEABLES ALTOS EN &HL 1051

ret
;>>>>>>>FIN SUMAR RESULTADO<<<<<<<<<<


.END
