.ORG 000H

	IN 00H					 		 ;ingresamos primer dato por puerto
	MOV C,A          	 	 ;guardamos el MULTIPLICANDO en el registro c
	IN 01H           	 	 ;ingresamos el segundo dato por puer 01h
  MOV D,A          	 	 ;GUARDAMOS EL MULTIPLICADOR EN EL REGISTRO D

	MVI H, 10H           ;Colocamos h en 10 para usarlo como apuntador
	MVI B, 08H       	 	 ;GUARDAMOS UN FFH EN EL REGISTRO B, ESTE NUMERO REPRESENTA LOS BITS A ROTAR

BitsARotar: MVI L,51H

		 MOV A,M 	         ;MOVEMOS EL NEABLE ALTO PARA ROTARLO
 			ANA A         	 ;DEJAMOS EL ACARREO EN 0
		 RAL            	 ;ROTAMOS A LA IZQUIERDA CON ACARREO
			MOV M,A       	 ;GUARDAMOS EL RESULTADO ROTADO EN E

			DCX H         	 ;DECREMENTAMOS &HL PARA OBTENER SU NEABLE BAJO
			MOV A,M 		  	 ;MOVEMOS EL NEABLE ALTO PARA ROTARLO
			ANA A     	     ;DEJAMOS EL ACARREO EN 0
			RAL        	     ;ROTAMOS A LA IZQUIERDA CON ACARREO
			MOV M,A     	   ;GUARDAMOS EL RESULTADO ROTADO EN E

 JNC AcaNeable     	   ;COMPROBAMOS SI HUBO ACARREO DEL NEABLE BAJO PARA SUMARLO AL NEABLE ALTO
 		INX H         	   ;INCREMENTAMOS &HL PARA USAR EL NEABLE ALTO
		MOV A,M       	   ;TRAEMOS EL CONTENIDO DIRECCIONADO POR &HL AL Acumulador
 		ACI 00H         	 ;SUMAMOS 00H + EL CONTENIDO DEL ACUMULADOR + EL ACARREO QUE DEJO EL NEABLE BAJO (SI LO HAY)
 		MOV M, A      		 ;GUARDAMOS EL RESULTADO EN EN EL NEABLE ALTO 1051H
    DCX H         		 ;VOLVEMOS AL NEABLE BAJO
 AcaNeable:MOV A,D		 ;TRAEMOS EL MULTIPLICADOR A "A"
  	 RAL               ;ROTAMOS EL MULTIPLICADOR
 	  MOV D,A            ;GUARDAMOS EL DATO ROTADO EN D

 JNC VerifAca    			 ;SI HAY ACARREO AL ROTAR EL MULTIPLICADOR, SUMAMOS EL MULTIPLICANDO
   ANA A          		 ;COLOCAMOS EL ACARREO EN CERO DENUEVO
   MOV A,C         	   ;SI HAY ACARREO PONEMOS EL MULTIPLICANDO EN EL ACUMULADOR
   ADD M							 ;Y LO SUMAMOS CON EL RESULTADO QUE ESTAMOS GUARDANDO EN E
	 MOV M,A             ;EL RESUSLTADO DE ESTO LO GUARDAMOS EN EL NEABLE BAJO

	 INX H               ;INCREMENTAMOS &HL PARA USAR EL NEABLE ALTO
		 MOV A,M           ;TRAEMOS EL CONTENIDO DIRECCIONADO POR &HL AL Acumulador
		 ACI 00H           ;SUMAMOS 00H + EL CONTENIDO DEL ACUMULADOR + EL ACARREO QUE DEJO EL NEABLE BAJO (SI LO HAY)
		 MOV M,A           ;GUARDAMOS EL RESULTADO EN EN EL NEABLE ALTO 1051H
 VerifAca:DCR B        ;SE DECREMENTA B

JNZ BitsARotar         ;COMPARAMOS SI B LLEGO A CERO PARA TERMINAR LOS SALOT


;MOSTRAMOS LOS RESULTADOS
MVI L,50H
MOV A,M                ;Movemos el resultado final al acumulador
OUT 08H                ;lo mostramos por el puerto 08h

INX H

MOV A,M
OUT 09H
HLT

.END
