.ORG 100H

  MVI H, 10H
  MVI L, 50H

  MVI M, 1EH
  INR L
  MVI M, 1CH

  MVI L, 50H
  MOV A, M
  INR	L
  SUB	M

  JNC POSITIVO                      ;SALTA SI EL RESULTADO ES POSITIVO

    MVI L, 51H
    MOV A, M
    MVI L, 50H
    SUB	M

    ;LLAMA ALGORIMO PARA MOSTRAR RESULTADO EN DISPLAY CON UNA MARQUITA PARA NUMERO NEGATIVO
    ;HLT TERMINA PROCESO

  POSITIVO:OUT 01H
  ;LLAMA ALGORITMO PARA MOSTRAR NUMEROS DE 1 O DOS UNIDADES
  HLT

.END
